name: "Issue Report"
description: "Use this form to report an issue. Please include the mod name in the title like this: [ModName] Your Issue Title"

body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to report an issue. Please remember, bugs are unintentional and your understanding is appreciated. Maintain a respectful tone throughout."
  - type: markdown
    attributes:
      value: "Please include the mod name in the title like this: [ModName] Your Issue Title"
  - type: input
    id: title
    attributes:
      label: "Title"
      placeholder: "[ModName] Describe your issue"
    validations:
      required: true
  - type: dropdown
    id: mod
    attributes:
      label: "Mod"
      description: "Choose the mod related to the issue."
      options:
        - "Vinery"
        - "NetherVinery"
        - "Meadow"
        - "Bakery"
        - "Candlelight"
        - "HerbalBrews"
        - "BloomingNature"
        - "WilderNature"
        - "Farm & Charm"
        - "Brewery"
        - "Beachparty"
        - "Camping"
        - "Furniture"
    validations:
      required: true
