name: Issue Report
description: Use this form to report an issue.

body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to report an issue. Please remember, bugs are unintentional and your understanding is appreciated. Maintain a respectful tone throughout."
  - type: markdown
    attributes:
      value: "Detail your issue below. 
      Please Note: This report form is intended for reporting issues and is not for general questions or assistance with uncertainties. For that, the wikis and Discord are available"
  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft Version
      placeholder: "e.g., 1.20.1"
    validations:
      required: true
  - type: dropdown
    id: mod
    attributes:
      label: Mod
      description: "Choose the mod related to the issue."
      options:
        - "Vinery"
        - "NetherVinery"
        - "Meadow"
        - "Bakery"
        - "Candlelight"
        - "HerbalBrews"
        - "BloomingNature"
        - "Farm and Charm"
        - "Brewery"
        - "Beachparty"
        - "Camping"
        - "Harvestfall"
        - "AppleWood"
        - "SafariBanquet"
        - "Seasonal Gifts"
        - "WilderNature"
        - "Lilis Lucky Lures"
        - "Furniture"
    validations:
      required: true
  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      placeholder: "e.g., 1.3.14"
    validations:
      required: true
  - type: checkboxes
    id: using_the_latest_version
    attributes:
      label: Latest Version
      description: "Are you using the latest version of the respective mod for the corresponding Minecraft version? Please note that older versions are no longer actively supported."
      options:
        - label: "Yes. I'm using the latest Version."
          required: true
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: "Provide a comprehensive description of the issue."
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: "Enumerate the steps needed to replicate the issue."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Upload logs via https://pastebin.com/ and provide the link here."
      validations:
        required: true
  - type: checkboxes
    id: has_tested_minimal_instance
    attributes:
      label: Minimal Instance Test
      description: "Check if the issue persists with only this mod and its dependencies active."
      options:
        - label: "Yes, I've tested on a minimal instance."
  - type: checkboxes
    id: has_checked_for_similar_issues
    attributes:
      label: Check for Similar Issues
      description: "Please verify if a similar issue has already been reported."
      options:
        - label: "Yes, I have checked for similar issues."
          required: true
