name: Suggestion
description: Suggest an improvement using this form.
body:
  - type: checkboxes
    id: currently_not_available
    attributes:
      label: "Currently no capacity for new suggestions."
      description: "Currently, I am unable to accept new suggestions. Please be aware that any new suggestions may be deleted. Sorry for the inconvenience."
      options:
        - label: "I understand that my suggestion might be deleted."
          required: true
  - type: markdown
    attributes:
      value: "What's your idea? Please describe it."
  - type: input
    id: mod
    attributes:
      label: Mod Name and Version
      placeholder: "e.g., Vinery"
    validations:
      required: true
  - type: textarea
    id: suggestion_detail
    attributes:
      label: Suggestion Details
      description: "Tell me more about your suggestion."
    validations:
      required: true
  - type: textarea
    id: expected_benefits
    attributes:
      label: Expected Benefits
      description: "What benefits do you think your suggestion will bring?"
    validations:
      required: true
  - type: textarea
    id: potential_drawbacks
    attributes:
      label: Potential Drawbacks
      description: "Any downsides to your idea?"
  - type: checkboxes
    id: has_checked_for_similar_suggestions
    attributes:
      label: Check for Similar Suggestions
      description: "Have you looked to see if someone else has suggested something similar?"
      options:
        - label: "Yes, I've looked for similar ideas."
          required: true
  - type: markdown
    attributes:
      value: "Thanks for your suggestion! I'll take a look and get back to you soon!"
