name: Suggestion
description: Suggest an improvement using this form.
body:
  - type: markdown
    attributes:
      value: "**🛑 Suggestions are currently closed! 🛑**\n\nThank you for your interest in improving our project. However, suggestions cannot be submitted at this time. Please check back later."
