name: Suggestion
description: Share your idea for future improvements!

body:
  - type: markdown
    attributes:
      value: |
        ### Currently Taking a Break from Suggestions
        Hi there! Thank you for wanting to share your ideas. 😊  
        At the moment, I don't have the capacity to review new suggestions. However, I really value your input and hope to revisit this in the future.  
        Feel free to check back later when suggestions are open again!
  
  - type: checkboxes
    id: understanding
    attributes:
      label: "Please confirm:"
      options:
        - label: "I understand that suggestions are currently on hold."
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: |
        Thank you for understanding!  
        I look forward to hearing your ideas in the future. 💡
